# how are fields used to move electrical energy

## electromagnetic induction

| name                      | symbol        | units     |
| ------------------------- | ------------- | --------- |
| magnetic flux             | $\Phi$        | $(Wb)$    |
| magnetic field strength   | $B$           | $(T)$     |
| area of loop              | $A$           | $(m^2)$   |
| electromotive force (EMF) | $\varepsilon$ | $(V)$     |
| length of wire            | $l$           | $(m)$     |
| velocity of wire          | $v$           | $(ms^-1)$ |

### magnetic flux

magnetic flux is the number of magnetic field lines passing through a surface (such as a loop of wire)

$$\Phi=B_\perp{A}$$

### faraday's law

faraday's law states that an EMF is generated in a current carrying loop equal to the negative rate of change of magnetic flux

rotating loop in a magnetic field

$$\varepsilon=n\frac{\Delta{\Phi}}{\Delta{t}}$$

wire moving in a magnetic field

$$\varepsilon=Blv$$

### lenz's law

lenz's law states that the direction of the induced current is such that the magnetic field of the current opposes the direction of the change in magnetic field.

### slip ring

slip ring is used to connect the loop to the rest of the circuit resulting in a continuous AC (alternating current)

### split ring

split ring commutator** reverses the direction of the current every half turn, flipping all the negative currents into positive currents making DC (direct current)

### RMS voltage

RMS voltage is the equivalent DC voltage that produces the same power in a load as the corresponding AC voltage

$$V_{RMS}=\frac{V_{peak}}{\sqrt{2}}$$

$$I_{RMS}=\frac{I_{peak}}{\sqrt{2}}$$

## power transmission

| name            | symbol | units      |
| --------------- | ------ | ---------- |
| power           | $P$    | $(W)$      |
| voltage         | $V$    | $(V)$      |
| current         | $I$    | $(A)$      |
| number of loops | $n$    |            |
| resistance      | $R$    | $(\Omega)$ |

### power

$$P=VI$$

### transformers

transformers is used to increase/decrease the voltage in a current to reduce power loss when transmitting power and it only works with AC Current.

$$P_\text{in}=P_\text{out}$$
$$V_{p}I_{p}=V_{s}I_{s}$$
$$\frac{I_s}{I_p}=\frac{V_p}{V_s}=\frac{n_p}{n_s}$$

### ohms Law

$$V=IR$$

### power loss

$$P_{\text{loss}}=I_\text{line}^2R_\text{line}$$

### voltage drop

$$V_\text{supply}=V_\text{load}+V_\text{drop}$$
$$V_\text{drop}=I_\text{line}R_\text{line}$$