# how fast can things go?

## motion

| name                     | symbol | units         |
| ------------------------ | ------ | ------------- |
| final velocity           | $v$    | $(ms^{-1})$   |
| initial velocity         | $u$    | $(ms^{-1})$   |
| acceleration             | $a$    | $(ms^{-2})$   |
| time                     | $t$    | $(s)$         |
| displacement             | $s$    | $(m)$         |
| centripetal acceleration | $a_c$  | $(ms^{-2})$   |
| centripetal force        | $F_c$  | $(N)$         |
| mass                     | $m$    | $(kg)$        |
| velocity                 | $v$    | $(ms^{-1})$   |
| distance                 | $r$    | $(m)$         |
| momentum                 | $p$    | $(kgms^{-1})$ |

### newton's three laws of motion

1. every object in a state of uniform motion will remain in that state of motion unless an external force acts on it
2. force equals mass times acceleration $F=ma$
3. for every action there is an equal and opposite reaction

### constant acceleration

$$v=u+at$$
$$v^2=u^2+2as$$
$$s=\frac{1}{2}(u+v)t$$
$$s=ut+\frac{1}{2}at^2$$
$$s=vt-\frac{1}{2}at^2$$

### circular motion

$$a_c=\frac{v^2}{r}$$

$$F_c=\frac{mv^2}{r}$$

### momentum

$$P=mv$$

conservation of momentum states that total momentum before and after a collision is equal

$$\sum{p_\text{initial}}=\sum{p_\text{final}}$$

## energy

energy is a measure of the ability of something to cause a change in the world and its unit is joules $(J)$

| name                           | symbol | units       |
| ------------------------------ | ------ | ----------- |
| kinetic energy                 | $E_k$  | $(J)$       |
| strain energy                  | $E_s$  | $(J)$       |
| gravitational potential energy | $E_g$  | $(J)$       |
| mass                           | $m$    | $(m)$       |
| velocity                       | $v$    | $(ms^{-1})$ |
| spring constant                | $k$    | $(Nm^{-1})$ |
| displacement                   | $x$    | $(m)$       |
| gravitational field strength   | $g$    | $(ms^{-2})$ |
| height above surface           | $h$    | $(m)$       |

$$E_k=\frac{1}{2}mv^2$$
$$E_s=\frac{1}{2}kx^2$$
$$E_g=mg\Delta{}h$$

### conservation of energy

conservation of energy states that total energy of an isolated system remains constant

$$\sum{E_\text{initial}}=\sum{E_\text{final}}$$

## special relativity

### einsteins two postulates

1. the laws of physics are the same in all inertial frames of reference
2. the speed of light in free space has the same value $c=3*10^8ms^{-1}$ in all inertial frames of reference

### frame of reference

frame of reference is a set of physical reference points that uniquely fix (locate and orient) the coordinate system and standardize measurements

an inertial frame of reference is a reference frame that is not accelerating

### lorentz factor

$$\gamma{}=\frac{1}{\sqrt{1-(\frac{v}{c})^2}}$$
$$v=c\sqrt{1-(\frac{1}{\gamma})^2}$$
as the velocity $v$ approaches the speed of light $c$, the lorentz factor $\gamma$ approaches $\infty$

```{r echo=FALSE}
desmos("y=\\frac{1}{\\sqrt{1-(\\frac{x}{c})^2}}$c=3")
```

the $x$ axis is scaled by a factor of $10^8$ so we can see the effect

### time dilation

proper time is the time interval between two events happening at the same location

$$t=t_0\gamma=\frac{t_0}{\sqrt{1-(\frac{v}{c})^2}}$$
$$v=c\sqrt{1-(\frac{t_0}{t})^2}$$

### length contraction

proper length is the length of an object as measured by an observer who is stationary relative to that object

$$L=\frac{L_0}{\gamma}=L_0\sqrt{1-(\frac{v}{c})^2}$$
$$v=c\sqrt{1-(\frac{L}{L_0})^2}$$

### mass energy

$$E_0=mc^2$$
$$E_\text{total}=E_0+E_k=\gamma{}mc^2$$
$$E_k=(\gamma{}-1)mc^2$$